In [1]:
import numpy as np
import pandas as pd

In [3]:
my_data = np.array([[0,3],[10,7],[20,9],[30,14],[40,15]])

In [4]:
print(my_data)

[[ 0  3]
 [10  7]
 [20  9]
 [30 14]
 [40 15]]


In [17]:
my_column_data = ['temperature','activity']

In [18]:
my_dataframe = pd.DataFrame(data=my_data,columns=my_column_data)

In [19]:
print(my_dataframe)

   temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15


In [20]:
my_dataframe["adjusted"] = my_dataframe["activity"]+2

In [21]:
print(my_dataframe)

   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11
3           30        14        16
4           40        15        17


In [22]:
print("Rows #0, #1, and #2:")
print(my_dataframe.head(3), '\n')

Rows #0, #1, and #2:
   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11 



In [23]:
print("Row #2:")
print(my_dataframe.iloc[[2]], '\n')

Row #2:
   temperature  activity  adjusted
2           20         9        11 



In [24]:
print("Rows #1, #2, and #3:")
print(my_dataframe[1:4], '\n')

Rows #1, #2, and #3:
   temperature  activity  adjusted
1           10         7         9
2           20         9        11
3           30        14        16 



In [26]:
print("Column 'temperature':")
print(my_dataframe['temperature'])

Column 'temperature':
0     0
1    10
2    20
3    30
4    40
Name: temperature, dtype: int32


In [27]:
my_col_data = ['Eleanor', 'Chidi', 'Tahani', 'Jason']

In [28]:
my_row_data = np.random.randint(low=0, high=100, size=(3,4))

In [29]:
print(my_col_data)

['Eleanor', 'Chidi', 'Tahani', 'Jason']


In [30]:
print(my_row_data)

[[28 85 67  8]
 [20 73 68 45]
 [66 64 48 42]]


In [31]:
myDF = pd.DataFrame(data=my_row_data, columns = my_col_data)
print(myDF)

   Eleanor  Chidi  Tahani  Jason
0       28     85      67      8
1       20     73      68     45
2       66     64      48     42


In [33]:
print(myDF['Eleanor'][1])

20


In [36]:
myDF['Janet'] = myDF['Tahani'] + myDF['Jason']

In [37]:
print(myDF)

   Eleanor  Chidi  Tahani  Jason  Janet
0       28     85      67      8     75
1       20     73      68     45    113
2       66     64      48     42     90


In [38]:
# Create a reference by assigning my_dataframe to a new variable.
print("Experiment with a reference:")
reference_to_df = df

# Print the starting value of a particular cell.
print("  Starting value of df: %d" % df['Jason'][1])
print("  Starting value of reference_to_df: %d\n" % reference_to_df['Jason'][1])

# Modify a cell in df.
df.at[1, 'Jason'] = df['Jason'][1] + 5
print("  Updated df: %d" % df['Jason'][1])
print("  Updated reference_to_df: %d\n\n" % reference_to_df['Jason'][1])

# Create a true copy of my_dataframe
print("Experiment with a true copy:")
copy_of_my_dataframe = my_dataframe.copy()

# Print the starting value of a particular cell.
print("  Starting value of my_dataframe: %d" % my_dataframe['activity'][1])
print("  Starting value of copy_of_my_dataframe: %d\n" % copy_of_my_dataframe['activity'][1])

# Modify a cell in df.
my_dataframe.at[1, 'activity'] = my_dataframe['activity'][1] + 3
print("  Updated my_dataframe: %d" % my_dataframe['activity'][1])
print("  copy_of_my_dataframe does not get updated: %d" % copy_of_my_dataframe['activity'][1])

Experiment with a reference:


NameError: name 'df' is not defined